import type { Metadata } from "next";
import "./globals.css";
import { IBM_Plex_Sans_Thai } from 'next/font/google';



const ibmPlexSans = IBM_Plex_Sans_Thai({
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-ibm-plex-sans-thai',
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${ibmPlexSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
